# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4b83918bff7a227c4df1699737afe043cf85e6c1a3508ec353401364ff1f4775a692c935382182a5e1e29e1b47aee29a9ad7f091d4cedc2687400534b19e0c

test:
  secret_key_base: 216a2573afa0e455e26f70216ad94f3d28c85b37c56b00cac2a22be8ebcd95d45ad5fe9e8ac2dfa7514a088ab2ed15b1b804ad06a5a472471796d99d749c21da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
